#!/bin/bash
cd ../out
# erl -eval 'G = {V, E} = caffe_graph:load(graph1), caffe:start( caffe:build( G, caffe:args_from_list( [ { V, { [ lamport_clock, vector_clock ], worker_random_messenger, #{ caffe_logging => [{graph_state, quiet}, {messenger, plugin_only}, {terminator, quiet}] } } } ] ) ) )'

erl -eval 'caffe:start(worker_scripted_event:load(test_chandy_lamport))'
